INSERT INTO team_user (id,
                       city,
                       country,
                       email,
                       house_nr,
                       last_name,
                       phone_nr,
                       state,
                       street,
                       sur_name,
                       zip_code,
                       profile_picture)
VALUES (1,
        'Berlin',
        'Germany',
        'behzad@behzad.de',
        '10',
        'karimi',
        '123456789',
        'berlin',
        'berlin street',
        'behzad',
        '12345',
        null);

INSERT INTO team_user (id,
                       city,
                       country,
                       email,
                       house_nr,
                       last_name,
                       phone_nr,
                       state,
                       street,
                       sur_name,
                       zip_code,
                       profile_picture)
VALUES (2,
        'Berlin',
        'Germany',
        'clarissa@clarissa.de',
        '12',
        'lachmann',
        '111111111',
        'popoland',
        'popo street',
        'clarissa',
        '11111',
        null)